name: ZMK Build

on:
  push:
    branches: [ main ]   # change to master if that's your default
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    secrets: inherit
